title:        Unquarked
tagline:      'Nerdspace by Dale Markowitz'
description:  'Nerdspace by Dale Markowitz'
url:          http://unquarked.com
version:      1.1.1
author:
  name:       ''
  email:      ''
#markdown:     liquid
permalink:    pretty
pygments:     true
paginate:     5
